# exclude SafeMath when calculating test coverage
# https://eth-brownie.readthedocs.io/en/v1.10.3/config.html#exclude_paths
reports:
  exclude_paths:
    - contracts/dependencies
    - contracts/base
#  exclude_contracts:
#    - SafeMath
#dependencies:
#  - smartcontractkit/chainlink-brownie-contracts@0.2.2
#  - OpenZeppelin/openzeppelin-contracts@4.3.2
compiler:
  solc:
    remappings:
      - "@chainlink=smartcontractkit/chainlink-brownie-contracts@0.2.2"
      - "@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.3.2"
# automatically fetch contract sources from Etherscan
autofetch_sources: True
# Uncomment to use the .env file
dotenv: .env
# set a custom mnemonic for the development network
networks:
  default: development
  development:
    rpc: "http://127.0.0.1:8546"
  ganache:
    rpc: "http://127.0.0.1:8545"
  rinkeby:
    rpc: ""
  mainnet-fork:
    rpc: ""
wallets:
  admin_from_key: ${ADMIN_PRIVATE_KEY}
  user1_from_key: ${USER1_PRIVATE_KEY}
  user2_from_key: ${USER2_PRIVATE_KEY}
  user3_from_key: ${USER3_PRIVATE_KEY}
  user4_from_key: ${USER4_PRIVATE_KEY}
  user5_from_key: ${USER5_PRIVATE_KEY}
  user6_from_key: ${USER6_PRIVATE_KEY}
#  from_mnemonic: ${MNEMONIC}

  # could also do from_mnemonic, and you'd have to change the accounts.add to accounts.from_mnemonic
